version: "3.9"

services:
  {{ cookiecutter.project_name.lower().replace(' ', '_').replace('-', '_') }}:
    container_name: "{{ cookiecutter.project_name.lower().replace(' ', '_').replace('-', '_') }}"
    image: "{{ cookiecutter.project_name.lower().replace(' ', '_').replace('-', '_') }}"
    build:
      context: .
      # context: https://github.com/martokk/{{ cookiecutter.project_name.lower().replace(' ', '_').replace('-', '_') }}.git#main
      target: production
    restart: unless-stopped
    # depends_on:
    #   - duckdns
    env_file:
      # - /home/ubuntu/volumes/{{ cookiecutter.project_name.lower().replace(' ', '_').replace('-', '_') }}/.env
      - ./{{ cookiecutter.project_name.lower().replace(' ', '_').replace('-', '_') }}/.env
    volumes:
      # - /home/ubuntu/volumes/{{ cookiecutter.project_name.lower().replace(' ', '_').replace('-', '_') }}/.env:/workspace/.env
      # - /home/ubuntu/volumes/{{ cookiecutter.project_name.lower().replace(' ', '_').replace('-', '_') }}/media:/workspace/media
      # - /home/ubuntu/volumes/{{ cookiecutter.project_name.lower().replace(' ', '_').replace('-', '_') }}/logs:/workspace/logs
      # - /home/ubuntu/volumes/{{ cookiecutter.project_name.lower().replace(' ', '_').replace('-', '_') }}/db.sqlite3:/workspace/db.sqlite3
      - ./{{ cookiecutter.project_name.lower().replace(' ', '_').replace('-', '_') }}:/workspace
    ports:
      - "8002:8002"
