version: "3.9"

services:
  { { cookiecutter.__project_module } }:
    container_name: "{{ cookiecutter.__project_module }}"
    image: "{{ cookiecutter.__project_module }}"
    build:
      context: .
      # context: https://github.com/martokk/{{ cookiecutter.__project_module }}.git#main
      target: production
    restart: unless-stopped
    # depends_on:
    #   - duckdns
    env_file:
      # - /home/ubuntu/volumes/{{ cookiecutter.__project_module }}/.env
      - ./{{ cookiecutter.__project_module }}/.env
    volumes:
      # - /home/ubuntu/volumes/{{ cookiecutter.__project_module }}/.env:/workspace/.env
      # - /home/ubuntu/volumes/{{ cookiecutter.__project_module }}/media:/workspace/media
      # - /home/ubuntu/volumes/{{ cookiecutter.__project_module }}/logs:/workspace/logs
      # - /home/ubuntu/volumes/{{ cookiecutter.__project_module }}/db.sqlite3:/workspace/db.sqlite3
      - ./{{ cookiecutter.__project_module }}:/{{ cookiecutter.__project_module }}
    ports:
      - "5000:5000"
